name: Deploy webapp

# Specify when the workflow should run
on:
    push:
      branches:
        - main  # This runs the workflow when code is pushed to the "main" branch
  
    workflow_dispatch:  # Allows the workflow to be triggered manually
  
  # Define the jobs that will be run
jobs:
    build:
        name: Build
        runs-on: ubuntu-latest
        steps:
          - name: Checkout code
            uses: actions/checkout@v3
    
          - name: Set up Node.js
            uses: actions/setup-node@v3
            with:
              node-version: '20.17'
    
          - name: Install dependencies
            run: npm install
    
          - name: Building project
            run: npm run build
    
          - name: Running tests
            run: npm run test

    deploy:
       name: Deploy
       needs: build
       runs-on: ubuntu-latest  # Use the latest Ubuntu environment for the action
       steps:

            # Step 5: Run the deploy script
            - name: Deploy to GitHub Pages
              run: |
                npx gh-pages -d build --user "maximlamare <32132761+maximlamare@users.noreply.github.com>" --message "Deploying to GitHub Pages"
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
